name: 'Build'

on:
  push:
    branches: [ 'main', 'master' ]
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    env:
      LISP: sbcl-bin

    steps:
      - uses: actions/checkout@v4

      - name: Install Lisp
        uses: 40ants/setup-lisp@v4
        with:
          asdf-system: wikidot-linter

      - name: Build Executable
        shell: bash
        run: |
          ros -e '(asdf:make :wikidot-linter)'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wikidot-linter-${{ matrix.os }}
          path: |
            wikidot-linter
            wikidot-linter.exe